### ISSUE TITLE
Put messages on the queue without diffing

### ISSUE THREAD

**Issue by wires** [histograph/import#4]
If you want to reindex data one currently needs to
- import with `--clear` flag; this puts **deletes** on the queue
- import without `--clear` flag; this puts the **adds** on the queue

Alternatively you can
- stop API
- delete API dir
- start API
- upload again

This will just push the **adds** to the queue. 

If would be nice if this can be overridden, so that without diffing, messages are pushed onto the queue. Graphmalizer is idempotent, meaning, adding the same thing twice will give the same result.

**Comment by bertspaan** [comment]
Done in e6af1bf278dc6f55fa04cf01872a5490f982c43b: `--force` option added! :facepunch:

**Comment by wires** [comment]
Vet :godmode:
